# Generated by Django 4.0 on 2021-12-19 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text_1', models.CharField(max_length=200, verbose_name='Основная информация')),
                ('text_2', models.TextField(verbose_name='Текст 1')),
                ('text_3', models.TextField(verbose_name='Текст 2')),
                ('image_1', models.ImageField(upload_to='about/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(upload_to='about/', verbose_name='Изображение 2')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('description', models.TextField(default='', verbose_name='Сообщение')),
                ('data', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время обращения')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Необязательное поле', max_length=50, verbose_name='Заголовок')),
                ('season', models.CharField(help_text='Необходимо для сортировки изображений на сайте', max_length=50, verbose_name='Сезон')),
                ('image', models.ImageField(help_text='Для корректного отображения на сайте, добавляйте горизонтальные изображения соотношением 2 к 1', upload_to='gallery/', verbose_name='Изображение')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок должен быть уникальныи, он будет служить для вас ориентиром в новостях и автоматически пропишется в URL', max_length=50, verbose_name='Заголовок')),
                ('anons', models.CharField(max_length=300, verbose_name='Анонс')),
                ('text', models.TextField(verbose_name='Новость')),
                ('image', models.ImageField(help_text='Для корректного отображения на сайте, добавляйте горизонтальные изображения соотношением 2 к 1', upload_to='news/', verbose_name='Изображение')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('draft', models.BooleanField(default=True, verbose_name='Публикация')),
                ('slug', models.SlugField(default='', help_text='URL для новости должен быть уникальным', unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время заказа')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Запись к инструкору',
                'verbose_name_plural': 'Записи к инструктору',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=100, verbose_name='Партнер')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Изображение')),
                ('adress', models.TextField(default='', verbose_name='Ссылка на партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Услуга')),
                ('season', models.CharField(max_length=50, verbose_name='Сезон')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='prices/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
