# Generated by Django 4.0 on 2021-12-11 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('number', models.CharField(max_length=12, verbose_name='Номер')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Заголовок')),
                ('season', models.CharField(default='', max_length=50, verbose_name='Сезон')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Заголовок')),
                ('anons', models.CharField(default='', max_length=300, verbose_name='Анонс')),
                ('text', models.TextField(default='', verbose_name='Новость')),
                ('image', models.ImageField(default='', upload_to='news/', verbose_name='Изображение')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('url', models.SlugField(default='', max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=100, verbose_name='Партнер')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Услуга')),
                ('season', models.CharField(default='', max_length=50, verbose_name='Сезон')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('price', models.CharField(default='', max_length=50, verbose_name='Сезон')),
                ('image', models.ImageField(upload_to='prices/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
