# Generated by Django 4.0 on 2021-12-20 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text_1',
            field=models.CharField(blank=True, help_text='Необязательное поле', max_length=200, verbose_name='Основная информация'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='anons',
            field=models.TextField(max_length=200, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(help_text='Добавьте изображение для отображения его на сайте', upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='Выберите шаблон для новости, загрузите избражение на сервер и введите размеры', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Заголовок должен быть уникальным и автоматически пропишется в URL', max_length=50, verbose_name='Заголовок'),
        ),
    ]
