# Generated by Django 4.0 on 2021-12-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='season',
            field=models.CharField(max_length=50, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='anons',
            field=models.CharField(max_length=300, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='season',
            field=models.CharField(max_length=50, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Услуга'),
        ),
    ]
