# Generated by Django 4.0 on 2021-12-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_text_1_alter_gallery_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['-date'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Запись к инструкору', 'verbose_name_plural': 'Записи к инструктору'},
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='season',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
