# Generated by Django 4.0 on 2021-12-10 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_date_news_poster_alter_news_full_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.RenameField(
            model_name='news',
            old_name='full_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='poster',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='news/', verbose_name='Изображение'),
        ),
    ]
