# Generated by Django 4.0 on 2021-12-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_alter_news_options_news_slug_alter_news_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='partners',
            name='adress',
            field=models.TextField(default='', verbose_name='Ссылка на партнера'),
        ),
        migrations.AlterField(
            model_name='news',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(help_text='Для корректного отображения на сайте, добавляйте горизонтальные изображения соотношением 2 к 1', upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='', help_text='URL для новости должен быть уникальным', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Заголовок должен быть уникальныи, он будет служить для вас ориентиром в новостях и автоматически пропишется в URL', max_length=50, verbose_name='Заголовок'),
        ),
    ]
