# Generated by Django 4.0 on 2021-12-20 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_gallery_date_alter_news_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices',
            options={'ordering': ['season'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.RemoveField(
            model_name='prices',
            name='price',
        ),
        migrations.AddField(
            model_name='prices',
            name='price_ad',
            field=models.CharField(blank=True, help_text='Необязательное поле', max_length=50, verbose_name='Цена взрослый'),
        ),
        migrations.AddField(
            model_name='prices',
            name='price_ch',
            field=models.CharField(blank=True, help_text='Необязательное поле', max_length=50, verbose_name='Цена детский'),
        ),
        migrations.AddField(
            model_name='prices',
            name='subscription',
            field=models.CharField(blank=True, help_text='Необязательное поле, заполняется в случае единого ценника, например на абонемент', max_length=50, verbose_name='Цена абонемент'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='По дате происходит сортировка изображений', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='По дате происходит сортировка новостей', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Новость'),
        ),
    ]
