# Generated by Django 4.0 on 2021-12-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_draft_news_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
    ]
