# Generated by Django 4.0 on 2021-12-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_prices_options_remove_prices_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='image',
            field=models.FileField(upload_to='prices/', verbose_name='Изображение'),
        ),
    ]
