# Generated by Django 4.0 on 2021-12-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_gallery_season_alter_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='season',
            field=models.CharField(default='', max_length=50, verbose_name='Сезон'),
        ),
    ]
